FROM jenkins/jenkins:lts-jdk17

USER root

RUN apt-get update && \
    apt-get install -y \
    ca-certificates \
    curl \
    git \
    docker.io \
    python3 \
    python3-pip \
    python3-venv \
    python3-pytest && \
    rm -rf /var/lib/apt/lists/*

ENV PATH="/usr/bin:${PATH}"

RUN which docker && docker --version

RUN usermod -aG docker jenkins

USER jenkins

RUN jenkins-plugin-cli --plugins \
    blueocean \
    docker-workflow \
    git \
    workflow-aggregator \
    junit \
    prometheus \
    metrics \
    pipeline-stage-view \
    credentials-binding